@host = http://localhost:5555
@userInfoRoute = api/v1/user/info
@signUpRoute = api/auth/signup
@signInRoute = api/auth/signin


GET {{host}}/{{userInfoRoute}}

### Authentication API - Sign Up
POST {{host}}/{{signUpRoute}} HTTP/1.1
content-type: application/json

{
  "username": "CapuchinoJT01",
  "email": "CapuchinoJT01@gmail.com",
  "password": "testpass"
}

### Authentication API - Sign Up
POST {{host}}/{{signInRoute}} HTTP/1.1
content-type: application/json

{
  "email": "CapuchinoJT01@gmail.com",
  "password": "testpass"
}
